[2024-08-18 11:49:55,867] {processor.py:153} INFO - Started process (PID=770926) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:49:55,867] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 11:49:55,868] {logging_mixin.py:115} INFO - [2024-08-18 11:49:55,867] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:49:55,885] {logging_mixin.py:115} INFO - [2024-08-18 11:49:55,884] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 11:49:55,885] {logging_mixin.py:115} INFO - [2024-08-18 11:49:55,885] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 11:49:55,885] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:49:55,897] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-08-18 11:50:32,495] {processor.py:153} INFO - Started process (PID=771418) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:50:32,496] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 11:50:32,496] {logging_mixin.py:115} INFO - [2024-08-18 11:50:32,496] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:50:32,515] {logging_mixin.py:115} INFO - [2024-08-18 11:50:32,515] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 11:50:32,515] {logging_mixin.py:115} INFO - [2024-08-18 11:50:32,515] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 11:50:32,516] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:50:32,532] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-08-18 11:51:07,262] {processor.py:153} INFO - Started process (PID=771833) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:51:07,271] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 11:51:07,272] {logging_mixin.py:115} INFO - [2024-08-18 11:51:07,272] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:51:07,298] {logging_mixin.py:115} INFO - [2024-08-18 11:51:07,298] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 11:51:07,299] {logging_mixin.py:115} INFO - [2024-08-18 11:51:07,299] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 11:51:07,299] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:51:07,317] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-08-18 11:51:42,408] {processor.py:153} INFO - Started process (PID=772232) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:51:42,414] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 11:51:42,415] {logging_mixin.py:115} INFO - [2024-08-18 11:51:42,415] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:51:42,470] {logging_mixin.py:115} INFO - [2024-08-18 11:51:42,469] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 11:51:42,470] {logging_mixin.py:115} INFO - [2024-08-18 11:51:42,470] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 11:51:42,471] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:51:42,508] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.116 seconds
[2024-08-18 11:52:17,788] {processor.py:153} INFO - Started process (PID=772976) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:52:17,792] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 11:52:17,793] {logging_mixin.py:115} INFO - [2024-08-18 11:52:17,793] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:52:17,823] {logging_mixin.py:115} INFO - [2024-08-18 11:52:17,823] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 11:52:17,823] {logging_mixin.py:115} INFO - [2024-08-18 11:52:17,823] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 11:52:17,823] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:52:17,853] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2024-08-18 11:52:50,184] {processor.py:153} INFO - Started process (PID=773345) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:52:50,195] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 11:52:50,196] {logging_mixin.py:115} INFO - [2024-08-18 11:52:50,196] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:52:50,228] {logging_mixin.py:115} INFO - [2024-08-18 11:52:50,227] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 11:52:50,228] {logging_mixin.py:115} INFO - [2024-08-18 11:52:50,228] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 11:52:50,228] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:52:50,259] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.079 seconds
[2024-08-18 11:53:23,455] {processor.py:153} INFO - Started process (PID=773734) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:53:23,456] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 11:53:23,456] {logging_mixin.py:115} INFO - [2024-08-18 11:53:23,456] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:53:23,482] {logging_mixin.py:115} INFO - [2024-08-18 11:53:23,482] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 11:53:23,483] {logging_mixin.py:115} INFO - [2024-08-18 11:53:23,482] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 11:53:23,483] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:53:23,511] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2024-08-18 11:53:56,871] {processor.py:153} INFO - Started process (PID=774139) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:53:56,876] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 11:53:56,876] {logging_mixin.py:115} INFO - [2024-08-18 11:53:56,876] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:53:56,904] {logging_mixin.py:115} INFO - [2024-08-18 11:53:56,904] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 11:53:56,904] {logging_mixin.py:115} INFO - [2024-08-18 11:53:56,904] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 11:53:56,904] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:53:56,934] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2024-08-18 11:54:30,727] {processor.py:153} INFO - Started process (PID=774518) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:54:30,731] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 11:54:30,732] {logging_mixin.py:115} INFO - [2024-08-18 11:54:30,732] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:54:30,755] {logging_mixin.py:115} INFO - [2024-08-18 11:54:30,754] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 11:54:30,755] {logging_mixin.py:115} INFO - [2024-08-18 11:54:30,755] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 11:54:30,755] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:54:30,773] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2024-08-18 11:55:02,675] {processor.py:153} INFO - Started process (PID=774936) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:55:02,681] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 11:55:02,682] {logging_mixin.py:115} INFO - [2024-08-18 11:55:02,682] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:55:02,715] {logging_mixin.py:115} INFO - [2024-08-18 11:55:02,714] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 11:55:02,715] {logging_mixin.py:115} INFO - [2024-08-18 11:55:02,715] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 11:55:02,715] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:55:02,732] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
[2024-08-18 11:55:35,077] {processor.py:153} INFO - Started process (PID=775299) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:55:35,078] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 11:55:35,078] {logging_mixin.py:115} INFO - [2024-08-18 11:55:35,078] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:55:35,109] {logging_mixin.py:115} INFO - [2024-08-18 11:55:35,108] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 11:55:35,109] {logging_mixin.py:115} INFO - [2024-08-18 11:55:35,109] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 11:55:35,109] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:55:35,120] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2024-08-18 11:56:11,520] {processor.py:153} INFO - Started process (PID=775730) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:56:11,521] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 11:56:11,521] {logging_mixin.py:115} INFO - [2024-08-18 11:56:11,521] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:56:11,539] {logging_mixin.py:115} INFO - [2024-08-18 11:56:11,539] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 11:56:11,539] {logging_mixin.py:115} INFO - [2024-08-18 11:56:11,539] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 11:56:11,539] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:56:11,561] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-08-18 11:56:46,677] {processor.py:153} INFO - Started process (PID=776126) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:56:46,677] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 11:56:46,678] {logging_mixin.py:115} INFO - [2024-08-18 11:56:46,678] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:56:46,706] {logging_mixin.py:115} INFO - [2024-08-18 11:56:46,706] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 11:56:46,706] {logging_mixin.py:115} INFO - [2024-08-18 11:56:46,706] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 11:56:46,706] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:56:46,727] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2024-08-18 11:57:21,480] {processor.py:153} INFO - Started process (PID=776524) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:57:21,481] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 11:57:21,481] {logging_mixin.py:115} INFO - [2024-08-18 11:57:21,481] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:57:21,501] {logging_mixin.py:115} INFO - [2024-08-18 11:57:21,501] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 11:57:21,502] {logging_mixin.py:115} INFO - [2024-08-18 11:57:21,502] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 11:57:21,502] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:57:21,514] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-08-18 11:57:55,908] {processor.py:153} INFO - Started process (PID=776898) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:57:55,913] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 11:57:55,914] {logging_mixin.py:115} INFO - [2024-08-18 11:57:55,914] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:57:55,930] {logging_mixin.py:115} INFO - [2024-08-18 11:57:55,930] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 11:57:55,930] {logging_mixin.py:115} INFO - [2024-08-18 11:57:55,930] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 11:57:55,930] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:57:55,960] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.054 seconds
[2024-08-18 11:58:34,950] {processor.py:153} INFO - Started process (PID=777327) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:58:34,955] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 11:58:34,955] {logging_mixin.py:115} INFO - [2024-08-18 11:58:34,955] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:58:34,991] {logging_mixin.py:115} INFO - [2024-08-18 11:58:34,991] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 11:58:34,992] {logging_mixin.py:115} INFO - [2024-08-18 11:58:34,992] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 11:58:34,992] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:58:35,016] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2024-08-18 11:59:11,304] {processor.py:153} INFO - Started process (PID=777767) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:59:11,309] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 11:59:11,310] {logging_mixin.py:115} INFO - [2024-08-18 11:59:11,309] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:59:11,365] {logging_mixin.py:115} INFO - [2024-08-18 11:59:11,364] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 11:59:11,365] {logging_mixin.py:115} INFO - [2024-08-18 11:59:11,365] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 11:59:11,365] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:59:11,392] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.092 seconds
[2024-08-18 11:59:46,501] {processor.py:153} INFO - Started process (PID=778147) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:59:46,505] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 11:59:46,506] {logging_mixin.py:115} INFO - [2024-08-18 11:59:46,506] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:59:46,529] {logging_mixin.py:115} INFO - [2024-08-18 11:59:46,529] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 11:59:46,529] {logging_mixin.py:115} INFO - [2024-08-18 11:59:46,529] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 11:59:46,530] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 11:59:46,546] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2024-08-18 12:02:33,467] {processor.py:153} INFO - Started process (PID=3542) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:02:33,468] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:02:33,468] {logging_mixin.py:115} INFO - [2024-08-18 12:02:33,468] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:02:33,479] {logging_mixin.py:115} INFO - [2024-08-18 12:02:33,479] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:02:33,479] {logging_mixin.py:115} INFO - [2024-08-18 12:02:33,479] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:02:33,479] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:02:33,487] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-08-18 12:02:59,955] {processor.py:153} INFO - Started process (PID=3881) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:02:59,956] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:02:59,956] {logging_mixin.py:115} INFO - [2024-08-18 12:02:59,956] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:02:59,970] {logging_mixin.py:115} INFO - [2024-08-18 12:02:59,970] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:02:59,971] {logging_mixin.py:115} INFO - [2024-08-18 12:02:59,970] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:02:59,971] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:02:59,981] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-08-18 12:03:35,635] {processor.py:153} INFO - Started process (PID=4650) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:03:35,636] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:03:35,637] {logging_mixin.py:115} INFO - [2024-08-18 12:03:35,637] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:03:35,650] {logging_mixin.py:115} INFO - [2024-08-18 12:03:35,650] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:03:35,650] {logging_mixin.py:115} INFO - [2024-08-18 12:03:35,650] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:03:35,651] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:03:35,658] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-08-18 12:04:09,495] {processor.py:153} INFO - Started process (PID=4930) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:04:09,495] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:04:09,496] {logging_mixin.py:115} INFO - [2024-08-18 12:04:09,496] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:04:09,512] {logging_mixin.py:115} INFO - [2024-08-18 12:04:09,511] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:04:09,512] {logging_mixin.py:115} INFO - [2024-08-18 12:04:09,512] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:04:09,512] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:04:09,523] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2024-08-18 12:04:43,209] {processor.py:153} INFO - Started process (PID=5095) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:04:43,210] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:04:43,211] {logging_mixin.py:115} INFO - [2024-08-18 12:04:43,211] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:04:43,225] {logging_mixin.py:115} INFO - [2024-08-18 12:04:43,224] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:04:43,225] {logging_mixin.py:115} INFO - [2024-08-18 12:04:43,225] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:04:43,225] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:04:43,236] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2024-08-18 12:05:15,879] {processor.py:153} INFO - Started process (PID=5269) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:05:15,880] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:05:15,880] {logging_mixin.py:115} INFO - [2024-08-18 12:05:15,880] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:05:15,894] {logging_mixin.py:115} INFO - [2024-08-18 12:05:15,893] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:05:15,894] {logging_mixin.py:115} INFO - [2024-08-18 12:05:15,894] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:05:15,894] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:05:15,904] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-08-18 12:05:47,665] {processor.py:153} INFO - Started process (PID=5435) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:05:47,666] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:05:47,667] {logging_mixin.py:115} INFO - [2024-08-18 12:05:47,667] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:05:47,681] {logging_mixin.py:115} INFO - [2024-08-18 12:05:47,680] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:05:47,681] {logging_mixin.py:115} INFO - [2024-08-18 12:05:47,681] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:05:47,681] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:05:47,692] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2024-08-18 12:06:20,255] {processor.py:153} INFO - Started process (PID=5611) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:06:20,255] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:06:20,256] {logging_mixin.py:115} INFO - [2024-08-18 12:06:20,256] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:06:20,269] {logging_mixin.py:115} INFO - [2024-08-18 12:06:20,268] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:06:20,269] {logging_mixin.py:115} INFO - [2024-08-18 12:06:20,269] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:06:20,269] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:06:20,278] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-08-18 12:06:53,845] {processor.py:153} INFO - Started process (PID=5783) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:06:53,846] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:06:53,846] {logging_mixin.py:115} INFO - [2024-08-18 12:06:53,846] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:06:53,863] {logging_mixin.py:115} INFO - [2024-08-18 12:06:53,863] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:06:53,863] {logging_mixin.py:115} INFO - [2024-08-18 12:06:53,863] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:06:53,863] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:06:53,874] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2024-08-18 12:07:25,822] {processor.py:153} INFO - Started process (PID=5949) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:07:25,823] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:07:25,824] {logging_mixin.py:115} INFO - [2024-08-18 12:07:25,823] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:07:25,837] {logging_mixin.py:115} INFO - [2024-08-18 12:07:25,837] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:07:25,837] {logging_mixin.py:115} INFO - [2024-08-18 12:07:25,837] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:07:25,838] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:07:25,847] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2024-08-18 12:07:59,012] {processor.py:153} INFO - Started process (PID=6166) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:07:59,013] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:07:59,014] {logging_mixin.py:115} INFO - [2024-08-18 12:07:59,014] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:07:59,029] {logging_mixin.py:115} INFO - [2024-08-18 12:07:59,029] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:07:59,030] {logging_mixin.py:115} INFO - [2024-08-18 12:07:59,029] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:07:59,030] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:07:59,040] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2024-08-18 12:08:30,979] {processor.py:153} INFO - Started process (PID=6335) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:08:30,979] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:08:30,980] {logging_mixin.py:115} INFO - [2024-08-18 12:08:30,980] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:08:30,993] {logging_mixin.py:115} INFO - [2024-08-18 12:08:30,992] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:08:30,993] {logging_mixin.py:115} INFO - [2024-08-18 12:08:30,993] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:08:30,993] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:08:31,001] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-08-18 12:09:03,573] {processor.py:153} INFO - Started process (PID=6494) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:09:03,574] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:09:03,574] {logging_mixin.py:115} INFO - [2024-08-18 12:09:03,574] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:09:03,587] {logging_mixin.py:115} INFO - [2024-08-18 12:09:03,587] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:09:03,587] {logging_mixin.py:115} INFO - [2024-08-18 12:09:03,587] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:09:03,587] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:09:03,598] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-08-18 12:09:37,067] {processor.py:153} INFO - Started process (PID=6669) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:09:37,067] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:09:37,068] {logging_mixin.py:115} INFO - [2024-08-18 12:09:37,068] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:09:37,082] {logging_mixin.py:115} INFO - [2024-08-18 12:09:37,081] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:09:37,082] {logging_mixin.py:115} INFO - [2024-08-18 12:09:37,082] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:09:37,082] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:09:37,096] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2024-08-18 12:10:09,602] {processor.py:153} INFO - Started process (PID=6834) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:10:09,603] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:10:09,604] {logging_mixin.py:115} INFO - [2024-08-18 12:10:09,603] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:10:09,617] {logging_mixin.py:115} INFO - [2024-08-18 12:10:09,617] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:10:09,618] {logging_mixin.py:115} INFO - [2024-08-18 12:10:09,617] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:10:09,618] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:10:09,627] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-08-18 12:10:42,911] {processor.py:153} INFO - Started process (PID=7003) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:10:42,913] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:10:42,914] {logging_mixin.py:115} INFO - [2024-08-18 12:10:42,914] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:10:42,928] {logging_mixin.py:115} INFO - [2024-08-18 12:10:42,927] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:10:42,928] {logging_mixin.py:115} INFO - [2024-08-18 12:10:42,928] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:10:42,928] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:10:42,938] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2024-08-18 12:11:15,372] {processor.py:153} INFO - Started process (PID=7171) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:11:15,374] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:11:15,376] {logging_mixin.py:115} INFO - [2024-08-18 12:11:15,375] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:11:15,395] {logging_mixin.py:115} INFO - [2024-08-18 12:11:15,394] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:11:15,395] {logging_mixin.py:115} INFO - [2024-08-18 12:11:15,395] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:11:15,395] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:11:15,409] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-08-18 12:11:48,495] {processor.py:153} INFO - Started process (PID=7330) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:11:48,497] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:11:48,499] {logging_mixin.py:115} INFO - [2024-08-18 12:11:48,499] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:11:48,519] {logging_mixin.py:115} INFO - [2024-08-18 12:11:48,518] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:11:48,519] {logging_mixin.py:115} INFO - [2024-08-18 12:11:48,519] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:11:48,520] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:11:48,541] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2024-08-18 12:12:22,935] {processor.py:153} INFO - Started process (PID=7495) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:12:22,936] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:12:22,937] {logging_mixin.py:115} INFO - [2024-08-18 12:12:22,937] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:12:22,954] {logging_mixin.py:115} INFO - [2024-08-18 12:12:22,953] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:12:22,954] {logging_mixin.py:115} INFO - [2024-08-18 12:12:22,954] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:12:22,954] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:12:22,966] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2024-08-18 12:12:55,149] {processor.py:153} INFO - Started process (PID=7705) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:12:55,150] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:12:55,151] {logging_mixin.py:115} INFO - [2024-08-18 12:12:55,150] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:12:55,165] {logging_mixin.py:115} INFO - [2024-08-18 12:12:55,165] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:12:55,165] {logging_mixin.py:115} INFO - [2024-08-18 12:12:55,165] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:12:55,165] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:12:55,176] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2024-08-18 12:13:26,300] {processor.py:153} INFO - Started process (PID=7870) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:13:26,301] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:13:26,302] {logging_mixin.py:115} INFO - [2024-08-18 12:13:26,301] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:13:26,314] {logging_mixin.py:115} INFO - [2024-08-18 12:13:26,314] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:13:26,314] {logging_mixin.py:115} INFO - [2024-08-18 12:13:26,314] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:13:26,315] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:13:26,325] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-08-18 12:13:57,268] {processor.py:153} INFO - Started process (PID=8022) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:13:57,268] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:13:57,269] {logging_mixin.py:115} INFO - [2024-08-18 12:13:57,269] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:13:57,286] {logging_mixin.py:115} INFO - [2024-08-18 12:13:57,286] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:13:57,287] {logging_mixin.py:115} INFO - [2024-08-18 12:13:57,287] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:13:57,289] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:13:57,300] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2024-08-18 12:14:29,943] {processor.py:153} INFO - Started process (PID=8191) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:14:29,944] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:14:29,945] {logging_mixin.py:115} INFO - [2024-08-18 12:14:29,944] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:14:29,961] {logging_mixin.py:115} INFO - [2024-08-18 12:14:29,961] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:14:29,961] {logging_mixin.py:115} INFO - [2024-08-18 12:14:29,961] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:14:29,961] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:14:29,971] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2024-08-18 12:15:05,038] {processor.py:153} INFO - Started process (PID=8363) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:15:05,039] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:15:05,039] {logging_mixin.py:115} INFO - [2024-08-18 12:15:05,039] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:15:05,054] {logging_mixin.py:115} INFO - [2024-08-18 12:15:05,054] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:15:05,054] {logging_mixin.py:115} INFO - [2024-08-18 12:15:05,054] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:15:05,055] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:15:05,067] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2024-08-18 12:15:38,305] {processor.py:153} INFO - Started process (PID=8542) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:15:38,308] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:15:38,308] {logging_mixin.py:115} INFO - [2024-08-18 12:15:38,308] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:15:38,333] {logging_mixin.py:115} INFO - [2024-08-18 12:15:38,333] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:15:38,333] {logging_mixin.py:115} INFO - [2024-08-18 12:15:38,333] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:15:38,333] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:15:38,345] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-08-18 12:16:10,811] {processor.py:153} INFO - Started process (PID=8709) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:16:10,812] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:16:10,812] {logging_mixin.py:115} INFO - [2024-08-18 12:16:10,812] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:16:10,825] {logging_mixin.py:115} INFO - [2024-08-18 12:16:10,825] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:16:10,825] {logging_mixin.py:115} INFO - [2024-08-18 12:16:10,825] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:16:10,826] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:16:10,834] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-08-18 12:16:41,553] {processor.py:153} INFO - Started process (PID=8860) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:16:41,553] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:16:41,554] {logging_mixin.py:115} INFO - [2024-08-18 12:16:41,554] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:16:41,568] {logging_mixin.py:115} INFO - [2024-08-18 12:16:41,568] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:16:41,568] {logging_mixin.py:115} INFO - [2024-08-18 12:16:41,568] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:16:41,569] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:16:41,585] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2024-08-18 12:17:13,423] {processor.py:153} INFO - Started process (PID=9029) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:17:13,424] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:17:13,424] {logging_mixin.py:115} INFO - [2024-08-18 12:17:13,424] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:17:13,437] {logging_mixin.py:115} INFO - [2024-08-18 12:17:13,437] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:17:13,437] {logging_mixin.py:115} INFO - [2024-08-18 12:17:13,437] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:17:13,437] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:17:13,448] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-08-18 12:17:46,636] {processor.py:153} INFO - Started process (PID=9192) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:17:46,637] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:17:46,637] {logging_mixin.py:115} INFO - [2024-08-18 12:17:46,637] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:17:46,654] {logging_mixin.py:115} INFO - [2024-08-18 12:17:46,653] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:17:46,654] {logging_mixin.py:115} INFO - [2024-08-18 12:17:46,654] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:17:46,654] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:17:46,667] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2024-08-18 12:18:19,071] {processor.py:153} INFO - Started process (PID=9415) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:18:19,072] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:18:19,073] {logging_mixin.py:115} INFO - [2024-08-18 12:18:19,073] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:18:19,095] {logging_mixin.py:115} INFO - [2024-08-18 12:18:19,093] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:18:19,095] {logging_mixin.py:115} INFO - [2024-08-18 12:18:19,095] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:18:19,096] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:18:19,109] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-08-18 12:18:52,336] {processor.py:153} INFO - Started process (PID=9578) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:18:52,336] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:18:52,337] {logging_mixin.py:115} INFO - [2024-08-18 12:18:52,337] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:18:52,349] {logging_mixin.py:115} INFO - [2024-08-18 12:18:52,348] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:18:52,349] {logging_mixin.py:115} INFO - [2024-08-18 12:18:52,349] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:18:52,349] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:18:52,361] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-08-18 12:19:27,162] {processor.py:153} INFO - Started process (PID=9754) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:19:27,163] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:19:27,164] {logging_mixin.py:115} INFO - [2024-08-18 12:19:27,164] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:19:27,177] {logging_mixin.py:115} INFO - [2024-08-18 12:19:27,176] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:19:27,177] {logging_mixin.py:115} INFO - [2024-08-18 12:19:27,177] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:19:27,177] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:19:27,187] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2024-08-18 12:19:59,076] {processor.py:153} INFO - Started process (PID=9910) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:19:59,077] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:19:59,082] {logging_mixin.py:115} INFO - [2024-08-18 12:19:59,081] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:19:59,097] {logging_mixin.py:115} INFO - [2024-08-18 12:19:59,097] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:19:59,098] {logging_mixin.py:115} INFO - [2024-08-18 12:19:59,098] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:19:59,098] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:19:59,111] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-08-18 12:20:32,110] {processor.py:153} INFO - Started process (PID=10078) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:20:32,111] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:20:32,113] {logging_mixin.py:115} INFO - [2024-08-18 12:20:32,112] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:20:32,131] {logging_mixin.py:115} INFO - [2024-08-18 12:20:32,131] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:20:32,131] {logging_mixin.py:115} INFO - [2024-08-18 12:20:32,131] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:20:32,131] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:20:32,140] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2024-08-18 12:21:04,766] {processor.py:153} INFO - Started process (PID=10249) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:21:04,767] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:21:04,768] {logging_mixin.py:115} INFO - [2024-08-18 12:21:04,768] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:21:04,780] {logging_mixin.py:115} INFO - [2024-08-18 12:21:04,780] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:21:04,781] {logging_mixin.py:115} INFO - [2024-08-18 12:21:04,781] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:21:04,781] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:21:04,790] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-08-18 12:21:37,936] {processor.py:153} INFO - Started process (PID=10421) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:21:37,937] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:21:37,937] {logging_mixin.py:115} INFO - [2024-08-18 12:21:37,937] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:21:37,955] {logging_mixin.py:115} INFO - [2024-08-18 12:21:37,955] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:21:37,956] {logging_mixin.py:115} INFO - [2024-08-18 12:21:37,956] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:21:37,956] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:21:37,967] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2024-08-18 12:22:11,686] {processor.py:153} INFO - Started process (PID=10594) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:22:11,687] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:22:11,688] {logging_mixin.py:115} INFO - [2024-08-18 12:22:11,688] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:22:11,704] {logging_mixin.py:115} INFO - [2024-08-18 12:22:11,703] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:22:11,704] {logging_mixin.py:115} INFO - [2024-08-18 12:22:11,704] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:22:11,704] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:22:11,718] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2024-08-18 12:22:43,727] {processor.py:153} INFO - Started process (PID=10754) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:22:43,728] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:22:43,728] {logging_mixin.py:115} INFO - [2024-08-18 12:22:43,728] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:22:43,744] {logging_mixin.py:115} INFO - [2024-08-18 12:22:43,743] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:22:43,744] {logging_mixin.py:115} INFO - [2024-08-18 12:22:43,744] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:22:43,744] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:22:43,758] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2024-08-18 12:23:15,856] {processor.py:153} INFO - Started process (PID=11027) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:23:15,857] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:23:15,857] {logging_mixin.py:115} INFO - [2024-08-18 12:23:15,857] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:23:15,873] {logging_mixin.py:115} INFO - [2024-08-18 12:23:15,872] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:23:15,873] {logging_mixin.py:115} INFO - [2024-08-18 12:23:15,873] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:23:15,873] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:23:15,885] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2024-08-18 12:23:50,075] {processor.py:153} INFO - Started process (PID=11194) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:23:50,077] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:23:50,077] {logging_mixin.py:115} INFO - [2024-08-18 12:23:50,077] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:23:50,102] {logging_mixin.py:115} INFO - [2024-08-18 12:23:50,102] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:23:50,103] {logging_mixin.py:115} INFO - [2024-08-18 12:23:50,103] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:23:50,103] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:23:50,118] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2024-08-18 12:24:23,874] {processor.py:153} INFO - Started process (PID=11367) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:24:23,875] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:24:23,876] {logging_mixin.py:115} INFO - [2024-08-18 12:24:23,876] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:24:23,891] {logging_mixin.py:115} INFO - [2024-08-18 12:24:23,891] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:24:23,892] {logging_mixin.py:115} INFO - [2024-08-18 12:24:23,892] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:24:23,892] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:24:23,908] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-08-18 12:24:55,318] {processor.py:153} INFO - Started process (PID=11524) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:24:55,319] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:24:55,320] {logging_mixin.py:115} INFO - [2024-08-18 12:24:55,319] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:24:55,334] {logging_mixin.py:115} INFO - [2024-08-18 12:24:55,334] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:24:55,334] {logging_mixin.py:115} INFO - [2024-08-18 12:24:55,334] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:24:55,335] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:24:55,348] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2024-08-18 12:25:26,611] {processor.py:153} INFO - Started process (PID=11684) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:25:26,612] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:25:26,612] {logging_mixin.py:115} INFO - [2024-08-18 12:25:26,612] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:25:26,640] {logging_mixin.py:115} INFO - [2024-08-18 12:25:26,639] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:25:26,640] {logging_mixin.py:115} INFO - [2024-08-18 12:25:26,640] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:25:26,641] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:25:26,653] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2024-08-18 12:25:59,311] {processor.py:153} INFO - Started process (PID=11845) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:25:59,311] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:25:59,312] {logging_mixin.py:115} INFO - [2024-08-18 12:25:59,312] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:25:59,326] {logging_mixin.py:115} INFO - [2024-08-18 12:25:59,325] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:25:59,326] {logging_mixin.py:115} INFO - [2024-08-18 12:25:59,326] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:25:59,326] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:25:59,335] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-08-18 12:26:30,876] {processor.py:153} INFO - Started process (PID=12008) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:26:30,877] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:26:30,878] {logging_mixin.py:115} INFO - [2024-08-18 12:26:30,878] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:26:30,896] {logging_mixin.py:115} INFO - [2024-08-18 12:26:30,896] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:26:30,896] {logging_mixin.py:115} INFO - [2024-08-18 12:26:30,896] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:26:30,896] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:26:30,908] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2024-08-18 12:27:04,438] {processor.py:153} INFO - Started process (PID=12171) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:27:04,438] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:27:04,439] {logging_mixin.py:115} INFO - [2024-08-18 12:27:04,439] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:27:04,455] {logging_mixin.py:115} INFO - [2024-08-18 12:27:04,455] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:27:04,456] {logging_mixin.py:115} INFO - [2024-08-18 12:27:04,456] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:27:04,456] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:27:04,467] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2024-08-18 12:27:36,531] {processor.py:153} INFO - Started process (PID=12339) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:27:36,532] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 12:27:36,533] {logging_mixin.py:115} INFO - [2024-08-18 12:27:36,533] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:27:36,544] {logging_mixin.py:115} INFO - [2024-08-18 12:27:36,544] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 12:27:36,545] {logging_mixin.py:115} INFO - [2024-08-18 12:27:36,545] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 12:27:36,545] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 12:27:36,553] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-08-18 19:40:31,476] {processor.py:153} INFO - Started process (PID=12860) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:40:31,478] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 19:40:31,479] {logging_mixin.py:115} INFO - [2024-08-18 19:40:31,479] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:40:31,495] {logging_mixin.py:115} INFO - [2024-08-18 19:40:31,495] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 19:40:31,496] {logging_mixin.py:115} INFO - [2024-08-18 19:40:31,496] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 19:40:31,496] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:40:31,509] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-08-18 19:41:04,929] {processor.py:153} INFO - Started process (PID=13363) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:41:04,930] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 19:41:04,930] {logging_mixin.py:115} INFO - [2024-08-18 19:41:04,930] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:41:04,948] {logging_mixin.py:115} INFO - [2024-08-18 19:41:04,947] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 19:41:04,948] {logging_mixin.py:115} INFO - [2024-08-18 19:41:04,948] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 19:41:04,949] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:41:04,956] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2024-08-18 19:41:38,434] {processor.py:153} INFO - Started process (PID=13534) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:41:38,435] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 19:41:38,435] {logging_mixin.py:115} INFO - [2024-08-18 19:41:38,435] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:41:38,448] {logging_mixin.py:115} INFO - [2024-08-18 19:41:38,448] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 19:41:38,448] {logging_mixin.py:115} INFO - [2024-08-18 19:41:38,448] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 19:41:38,448] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:41:38,458] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-08-18 19:42:12,049] {processor.py:153} INFO - Started process (PID=13694) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:42:12,051] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 19:42:12,052] {logging_mixin.py:115} INFO - [2024-08-18 19:42:12,052] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:42:12,069] {logging_mixin.py:115} INFO - [2024-08-18 19:42:12,069] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 19:42:12,069] {logging_mixin.py:115} INFO - [2024-08-18 19:42:12,069] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 19:42:12,069] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:42:12,080] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-08-18 19:42:45,383] {processor.py:153} INFO - Started process (PID=13875) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:42:45,384] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 19:42:45,384] {logging_mixin.py:115} INFO - [2024-08-18 19:42:45,384] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:42:45,396] {logging_mixin.py:115} INFO - [2024-08-18 19:42:45,396] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 19:42:45,396] {logging_mixin.py:115} INFO - [2024-08-18 19:42:45,396] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 19:42:45,396] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:42:45,405] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-08-18 19:43:18,680] {processor.py:153} INFO - Started process (PID=14038) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:43:18,681] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 19:43:18,682] {logging_mixin.py:115} INFO - [2024-08-18 19:43:18,682] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:43:18,697] {logging_mixin.py:115} INFO - [2024-08-18 19:43:18,697] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 19:43:18,697] {logging_mixin.py:115} INFO - [2024-08-18 19:43:18,697] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 19:43:18,697] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:43:18,705] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2024-08-18 19:43:50,982] {processor.py:153} INFO - Started process (PID=14204) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:43:50,983] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 19:43:50,984] {logging_mixin.py:115} INFO - [2024-08-18 19:43:50,984] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:43:51,000] {logging_mixin.py:115} INFO - [2024-08-18 19:43:50,999] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 19:43:51,000] {logging_mixin.py:115} INFO - [2024-08-18 19:43:51,000] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 19:43:51,000] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:43:51,009] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2024-08-18 19:44:23,097] {processor.py:153} INFO - Started process (PID=14424) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:44:23,099] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 19:44:23,101] {logging_mixin.py:115} INFO - [2024-08-18 19:44:23,100] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:44:23,114] {logging_mixin.py:115} INFO - [2024-08-18 19:44:23,114] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 19:44:23,114] {logging_mixin.py:115} INFO - [2024-08-18 19:44:23,114] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 19:44:23,114] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:44:23,125] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2024-08-18 19:44:54,559] {processor.py:153} INFO - Started process (PID=14635) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:44:54,560] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 19:44:54,561] {logging_mixin.py:115} INFO - [2024-08-18 19:44:54,561] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:44:54,572] {logging_mixin.py:115} INFO - [2024-08-18 19:44:54,572] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 19:44:54,573] {logging_mixin.py:115} INFO - [2024-08-18 19:44:54,572] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 19:44:54,573] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:44:54,582] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-08-18 19:45:30,020] {processor.py:153} INFO - Started process (PID=14863) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:45:30,021] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-18 19:45:30,021] {logging_mixin.py:115} INFO - [2024-08-18 19:45:30,021] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:45:30,036] {logging_mixin.py:115} INFO - [2024-08-18 19:45:30,035] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-18 19:45:30,036] {logging_mixin.py:115} INFO - [2024-08-18 19:45:30,036] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-18 19:45:30,036] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-18 19:45:30,047] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
